import { ModuleHeader } from '../components/UI'
import { useState } from 'react'
import { Search } from 'lucide-react'

const terms: { term: string; category: string; def: string }[] = [
  { term: '802.11', category: 'WiFi', def: 'The IEEE standard defining wireless LAN communications. Sub-variants: 802.11a/b/g/n (WiFi 4) / ac (WiFi 5) / ax (WiFi 6) / be (WiFi 7).' },
  { term: '802.11w / MFP', category: 'WiFi', def: 'Management Frame Protection. Authenticates management frames (deauth, disassoc) using derived keys. Prevents deauth attacks against compliant clients.' },
  { term: 'ANonce', category: 'WPA2', def: 'Authenticator Nonce — a random 32-byte value generated by the AP in WPA2 4-way handshake message 1. Used in PTK derivation.' },
  { term: 'ARP', category: 'Network', def: 'Address Resolution Protocol. Maps IP addresses to MAC addresses on a local network segment. Target of ARP poisoning/spoofing attacks.' },
  { term: 'BSSID', category: 'WiFi', def: 'Basic Service Set Identifier. The MAC address of an Access Point (AP). Each AP has a globally unique BSSID (though it can be spoofed).' },
  { term: 'BadUSB', category: 'USB', def: 'Attack where a device presents itself as a USB keyboard (HID) and injects keystrokes automatically, bypassing OS trust mechanisms.' },
  { term: 'Beacon Frame', category: 'WiFi', def: '802.11 management frame broadcast ~10x/sec by APs to announce their presence. Contains SSID, BSSID, channel, supported rates, and security capabilities.' },
  { term: 'BLE', category: 'Bluetooth', def: 'Bluetooth Low Energy. Lower power variant of Bluetooth optimized for IoT devices, wearables, beacons. Operates at 2.4 GHz in 40 x 2 MHz channels.' },
  { term: 'CCMP/AES', category: 'WPA2', def: 'Counter Mode CBC-MAC Protocol with AES-128. The encryption algorithm used by WPA2 for data frames. Replaced vulnerable TKIP from WPA.' },
  { term: 'CSMA/CA', category: 'WiFi', def: 'Carrier Sense Multiple Access with Collision Avoidance. WiFi medium access method — devices listen before transmitting and back off randomly if the channel is busy.' },
  { term: 'Captive Portal', category: 'Attack', def: 'A web page that intercepts all HTTP requests and redirects users to it before allowing network access. Used by hotels, airports, and by attackers to harvest credentials.' },
  { term: 'Channel Hopping', category: 'WiFi', def: 'Rapidly switching between 802.11 channels to scan all available channels. Trade-off: dwell time per channel determines detection reliability.' },
  { term: 'DHCP', category: 'Network', def: 'Dynamic Host Configuration Protocol. Automatically assigns IP addresses, gateway, and DNS server to devices joining a network. UDP ports 67/68.' },
  { term: 'DHCP Snooping', category: 'Defense', def: 'Switch security feature that only allows DHCP offer packets from trusted (uplink) ports. Prevents rogue DHCP server attacks.' },
  { term: 'DNS', category: 'Network', def: 'Domain Name System. Translates human-readable domain names to IP addresses. The internet\'s phone book. UDP/TCP port 53.' },
  { term: 'DNS Hijacking', category: 'Attack', def: 'Manipulating DNS responses to redirect domain names to attacker-controlled IP addresses. Combined with rogue DHCP for full MITM position.' },
  { term: 'DORA', category: 'Network', def: 'DHCP sequence: Discover (client broadcasts) → Offer (server responds) → Request (client confirms) → Acknowledge (server confirms lease).' },
  { term: 'EAPOL', category: 'WPA2', def: 'Extensible Authentication Protocol over LAN. The frame format carrying the WPA2 4-way handshake messages.' },
  { term: 'ESP-NOW', category: 'Hardware', def: 'Espressif proprietary direct WiFi communication protocol. Allows ESP32 devices to communicate without AP association, directly peer-to-peer.' },
  { term: 'ESP32-S3', category: 'Hardware', def: 'Espressif Systems dual-core Xtensa LX7 microcontroller at 240 MHz with integrated WiFi (802.11 b/g/n) and Bluetooth 5. Used in the Cardputer.' },
  { term: 'Evil Twin', category: 'Attack', def: 'Rogue AP that impersonates a legitimate AP using the same SSID (and optionally BSSID). Attracts clients away from the real AP.' },
  { term: 'FCS', category: 'WiFi', def: 'Frame Check Sequence. 4-byte CRC at the end of every 802.11 frame for error detection. Not the same as authentication.' },
  { term: 'GTK', category: 'WPA2', def: 'Group Temporal Key. Sent by AP to client in WPA2 handshake message 3 (encrypted). Used for broadcast/multicast frame encryption.' },
  { term: 'HID', category: 'USB', def: 'Human Interface Device. USB device class for keyboards, mice, gamepads. Trusted by all OSes without driver installation. Exploited by BadUSB.' },
  { term: 'HMAC', category: 'Crypto', def: 'Hash-based Message Authentication Code. Used in WPA2 for MIC (Message Integrity Code) verification during the 4-way handshake.' },
  { term: 'Hashcat', category: 'Tool', def: 'GPU-accelerated password recovery tool supporting hundreds of hash types including WPA2-PBKDF2, NTLMv2, MD5. -m 22000 for WPA2, -m 5600 for NTLMv2.' },
  { term: 'IMSI', category: 'Cellular', def: 'International Mobile Subscriber Identity. 15-digit number uniquely identifying a SIM card globally. Format: MCC + MNC + MSIN.' },
  { term: 'Karma Attack', category: 'Attack', def: 'AP responds to any probe request, claiming to be the requested SSID. Attracts devices probing for remembered networks.' },
  { term: 'LDAP', category: 'Network', def: 'Lightweight Directory Access Protocol. Used by Active Directory to store and query user accounts, groups, policies. Port 389 (636 for LDAPS).' },
  { term: 'LLMNR', category: 'Network', def: 'Link-Local Multicast Name Resolution. Windows name resolution fallback when DNS fails. Broadcasts over 224.0.0.252. Exploited by Responder.' },
  { term: 'MAC Address', category: 'Network', def: 'Media Access Control address. 6-byte hardware identifier for network interfaces. Globally unique (though software-spoofable). Format: AA:BB:CC:DD:EE:FF.' },
  { term: 'MAC Randomization', category: 'Privacy', def: 'iOS/Android feature that uses random MACs for WiFi probe requests and connections. Partially mitigates tracking, but SSIDs in probes still leak.' },
  { term: 'MIC', category: 'WPA2', def: 'Message Integrity Code. HMAC-based authentication code included in EAPOL handshake frames. Proves the sender derived the correct PTK.' },
  { term: 'MITM', category: 'Attack', def: 'Man-in-the-Middle. Attacker intercepts and can read/modify traffic between two parties. Achieved via ARP poisoning, rogue DHCP, evil twin, or similar.' },
  { term: 'NBT-NS', category: 'Network', def: 'NetBIOS Name Service. Windows name resolution via UDP port 137. Broadcasts name queries on the local subnet. Exploited by Responder.' },
  { term: 'NTLM', category: 'Network', def: 'NT LAN Manager. Windows authentication protocol using challenge-response. NTLMv2 is current version. Hashes capturable via Responder for offline cracking.' },
  { term: 'OWE', category: 'WPA3', def: 'Opportunistic Wireless Encryption. WPA3 feature providing encryption on open networks without a password. Prevents passive sniffing on "free WiFi".' },
  { term: 'PBKDF2', category: 'Crypto', def: 'Password-Based Key Derivation Function 2. Used by WPA2 to derive the PMK from the passphrase and SSID. 4096 iterations of HMAC-SHA1.' },
  { term: 'PMK', category: 'WPA2', def: 'Pairwise Master Key. Derived from the WiFi password via PBKDF2. Root key from which the PTK is derived. 256 bits.' },
  { term: 'PMKID', category: 'WPA2', def: 'A cryptographic identifier included in EAPOL MSG1 by the AP. Can be captured and cracked offline without a client present.' },
  { term: 'PTK', category: 'WPA2', def: 'Pairwise Transient Key. Session key derived from PMK + ANonce + SNonce + MACs. Used to encrypt unicast data frames and verify MICs.' },
  { term: 'Probe Request', category: 'WiFi', def: '802.11 management frame sent by clients asking "is [SSID] around?" for every network in their Preferred Network List. Major privacy leak.' },
  { term: 'Promiscuous Mode', category: 'WiFi', def: 'WiFi radio mode where the device receives all 802.11 frames in range, not just those addressed to itself. Also called monitor mode.' },
  { term: 'RSSI', category: 'WiFi', def: 'Received Signal Strength Indicator. Measured in dBm (negative values; −30 = strong, −90 = weak). Determines which AP a device connects to in auto-select.' },
  { term: 'RFUnit', category: 'Hardware', def: 'M5Stack expansion module with CC1101 sub-GHz transceiver. Supports 315/433/868/915 MHz for RF signal capture and replay.' },
  { term: 'Responder', category: 'Tool', def: 'Open-source tool that poisons LLMNR and NBT-NS queries to capture NTLMv2 credential hashes. Evil-M5 includes a Cardputer port.' },
  { term: 'SAE / Dragonfly', category: 'WPA3', def: 'Simultaneous Authentication of Equals. WPA3 key exchange that replaces PSK. Zero-knowledge proof means captured handshakes cannot be dictionary attacked.' },
  { term: 'SSID', category: 'WiFi', def: 'Service Set Identifier. The human-readable name of a WiFi network (up to 32 octets). Can contain any printable character including spaces.' },
  { term: 'SSDP', category: 'Network', def: 'Simple Service Discovery Protocol. UPnP discovery layer. Multicast on 239.255.255.250 port 1900. Used by smart devices to announce themselves.' },
  { term: 'SSL Stripping', category: 'Attack', def: 'MITM technique that downgrades HTTPS connections to HTTP by intercepting redirects. Largely mitigated by HSTS preloading in modern browsers.' },
  { term: 'SNonce', category: 'WPA2', def: 'Supplicant Nonce — random 32-byte value generated by the client in WPA2 handshake message 2. Used with ANonce in PTK derivation.' },
  { term: 'TLS', category: 'Crypto', def: 'Transport Layer Security. Protocol providing encrypted end-to-end communication (HTTPS). Operates at Layer 5/6 — above WiFi\'s Layer 2. Protects content from WiFi MITM.' },
  { term: 'UPnP', category: 'Network', def: 'Universal Plug and Play. Protocol for automatic device discovery and service configuration on a network. Frequently misconfigured, enabling port mapping abuse.' },
  { term: 'WPA2', category: 'WiFi', def: 'WiFi Protected Access 2. Current dominant WiFi security standard. Uses CCMP/AES encryption and PBKDF2-based PSK or 802.1X enterprise authentication.' },
  { term: 'WPA3', category: 'WiFi', def: 'WiFi Protected Access 3. Successor to WPA2. Adds SAE, MFP, OWE. Significantly harder to attack but rare in practice (2024).' },
  { term: 'WPAD', category: 'Network', def: 'Web Proxy Auto-Discovery Protocol. Windows mechanism for automatic proxy configuration. Broadcasts DNS/LLMNR queries for wpad.local. Exploited by Responder.' },
  { term: 'Wardriving', category: 'Recon', def: 'Mobile WiFi network scanning while physically moving through an area. Typically combined with GPS to log network locations.' },
  { term: 'Wireshark', category: 'Tool', def: 'Open-source network packet analyzer. Used to analyze .pcap files captured by the Cardputer. Supports all 802.11 frame dissection.' },
  { term: 'hashcat', category: 'Tool', def: 'GPU-accelerated hash cracker. Mode -m 22000 for WPA2 PBKDF2, -m 5600 for NTLMv2. Essential for offline cracking of captured material.' },
]

const categories = ['All', ...Array.from(new Set(terms.map(t => t.category))).sort()]

const catColors: Record<string, string> = {
  WiFi:     'var(--color-steel)',
  WPA2:     'var(--color-amber)',
  WPA3:     'var(--color-green)',
  Attack:   'var(--color-red)',
  Network:  'var(--color-steel)',
  Hardware: 'var(--color-violet)',
  USB:      'var(--color-violet)',
  Bluetooth:'var(--color-violet)',
  Crypto:   'var(--color-amber)',
  Tool:     'var(--color-green)',
  Recon:    'var(--color-steel)',
  Privacy:  'var(--color-text-muted)',
  Defense:  'var(--color-green)',
  Cellular: 'var(--color-red)',
}

export default function ModuleGlossary() {
  const [search, setSearch] = useState('')
  const [cat, setCat] = useState('All')

  const filtered = terms.filter(t => {
    const matchCat = cat === 'All' || t.category === cat
    const matchSearch = !search || t.term.toLowerCase().includes(search.toLowerCase()) || t.def.toLowerCase().includes(search.toLowerCase())
    return matchCat && matchSearch
  })

  return (
    <div>
      <ModuleHeader
        num="09"
        title="Glossary"
        subtitle="Quick reference for key technical terms used throughout this manual — from 802.11 frame types to cryptographic primitives."
      />

      {/* Search + filter */}
      <div className="flex flex-col sm:flex-row gap-3 mb-6">
        <div className="relative flex-1">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: 'var(--color-text-faint)' }} />
          <input
            type="text"
            placeholder="Search terms…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 rounded-lg text-sm outline-none"
            style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', color: 'var(--color-text)', fontFamily: 'var(--font-body)' }}
          />
        </div>
        <div className="flex flex-wrap gap-1.5">
          {categories.map(c => (
            <button
              key={c}
              onClick={() => setCat(c)}
              className="px-2.5 py-1 rounded text-[10px] font-semibold transition-colors"
              style={{
                background: cat === c ? (catColors[c] || 'var(--color-amber)') + '33' : 'var(--color-surface)',
                border: `1px solid ${cat === c ? (catColors[c] || 'var(--color-amber)') : 'var(--color-border-subtle)'}`,
                color: cat === c ? (catColors[c] || 'var(--color-amber)') : 'var(--color-text-faint)',
                fontFamily: 'var(--font-display)',
              }}
            >
              {c}
            </button>
          ))}
        </div>
      </div>

      <div className="text-xs mb-4" style={{ color: 'var(--color-text-faint)' }}>
        {filtered.length} of {terms.length} terms
      </div>

      {/* Term list */}
      <div className="space-y-1">
        {filtered.map(t => (
          <div key={t.term} className="flex gap-4 p-3 rounded-lg" style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border-subtle)' }}>
            <div style={{ minWidth: '130px', flexShrink: 0 }}>
              <div className="text-sm font-bold" style={{ color: catColors[t.category] || 'var(--color-amber)', fontFamily: 'var(--font-display)' }}>{t.term}</div>
              <div className="text-[9px] uppercase tracking-wider mt-0.5" style={{ color: 'var(--color-text-faint)' }}>{t.category}</div>
            </div>
            <div className="text-sm" style={{ color: 'var(--color-text-muted)', lineHeight: '1.6' }}>{t.def}</div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="text-center py-10 text-sm" style={{ color: 'var(--color-text-faint)' }}>
            No terms match "{search}"
          </div>
        )}
      </div>
    </div>
  )
}
